baseURL = "https://jindiamond.github.io"
languageCode = "en-us"
title = "精鑽股份有限公司"
theme = "hugo-arcana"
copyright = "台中巿豐原區北陽路339巷20號2F TEL:04-25239551"

defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        weight = 2
    [languages.es]
        languageName = "Spanish"
        weight = 3

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Useful Links"
        [[params.footer.links.links]]
            title = "Home"
            url = "#"
        [[params.footer.links.links]]
            title = "Case Studies"
            url = "#"
        [[params.footer.links.links]]
            title = "Plasma Technology"
            url = "#"
        [[params.footer.links.links]]
            title = "News & Events"
            url = "#"
        [[params.footer.links.links]]
            title = "About Us"
            url = "#"
        [[params.footer.links.links]]
            title = "Services"
            url = "#"
        [[params.footer.links.links]]
            title = "Products & Services"
            url = "#"

        [[params.footer.links]]
            header = "精鑽股份有限公司 "
        [[params.footer.links.links]]
            title = "統一編號:22120964"
            url = "#"
        [[params.footer.links.links]]
            title = "Email:mason.jindiamond@gmail.com"
            url = "#"
        [[params.footer.links.links]]
            title = "TEL:+886-934303507"
            url = "#"
        [[params.footer.links.links]]
            title = "FAX:+886-4-25230646"
            url = "#"
        [[params.footer.links.links]]
            title = "地址:台中巿豐原區北陽路339巷20號2F"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
