[[main]]
    name = "產品"
    weight = 3000
    url = "/right-sidebar"
[[main]]
    parent = "產品"
    name = "磁控濺射源 >>"
    weight = 40
    url = "/sputter"

[[main]]
    parent = "磁控濺射源 >>"
    name = "矩型靶源"
    weight = 41
    url = "../left-sidebar--sputter--rect"
[[main]]
    parent = "磁控濺射源 >>"
    name = "圓型靶源"
    weight = 42
    url = "../left-sidebar"
[[main]]
    parent = "磁控濺射源 >>"
    name = "旋轉圓柱靶源"
    weight = 43
    url = "../left-sidebar"


[[main]]
    parent = "產品"
    name = "離子源  >>"
    weight = 50
    url = "/IOB"
[[main]]
    parent = "離子源  >>"
    name = "矩型離子源"
    weight = 51
    url = "../left-sidebar"
[[main]]
    parent = "離子源  >>"
    name = "圓型離子源"
    weight = 52
    url = "../left-sidebar"
[[main]]
    parent = "離子源  >>"
    name = "RF式離子源"
    weight = 53
    url = "../left-sidebar"
[[main]]
    parent = "離子源  >>"
    name = "Filment式離子源"
    weight = 53
    url = "../left-sidebar"





[[main]]
    parent = "產品"
    name = "高溫爐"
    weight = 60
[[main]]
    parent = "產品"
    name = "大氣電漿"
    weight = 70
[[main]]
    parent = "大氣電漿"
    name = "Jet Type"
    identifier = "sub-lorem"
    weight = 35
[[main]]
    parent = "大氣電漿"
    name = "DBD"
    weight = 36
[[main]]
    parent = "大氣電漿"
    name = "Magna phasellus"
    weight = 37
[[main]]
    parent = "大氣電漿"
    name = "Etiam nisl"
    weight = 38
[[main]]
    parent = "大氣電漿"
    name = "Veroeros feugiat"
    identifier = "sub-veroeros"
    weight = 39

[[main]]
    name = "About"
    weight = 90

[[main]]
    parent = "About"
    name = "Data01"
    weight = 91
[[main]]
    parent = "About"
    name = "Data02"
    weight = 92
